image: Visual Studio 2017

skip_commits:
  files:
    - '**/*.md'

build_script:
  - cmd: pack.cmd 1.1.0-alpha.%APPVEYOR_BUILD_NUMBER%

artifacts:
  - path: 'Packages\*.nupkg'

deploy:
  provider: NuGet
  server: https://www.myget.org/F/msbuildsdkextras/api/v2/package
  api_key:
    secure: bmqlJK8a5HYiUXOT99HXT1j7JiM5+fpR4kHhxIC30oaaEXbv94f0fKdiKlU1QC/l
  artifact: /.*\.nupkg/
